spring:
  datasource:
    url: jdbc:h2:mem:inventory
    driverClassName: org.h2.Driver
    username: sa
    password:
  mail:
    host: ${SPRING_MAIL_HOST}
    port: ${SPRING_MAIL_PORT}
    username: ${SMTP_USERNAME}
    password: ${SMTP_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  jpa:
    hibernate:
      ddl-auto: create
  h2:
    console:
      enabled: true
      path: /h2-console

jwt:
  secret: ${JWT_SECRET}
  expiration: 3600000 # 1 hour

app:
  verification:
    uri: http://localhost:3000/verify?token=