spring:
  datasource:
    url: jdbc:h2:mem:inventory
    driverClassName: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: create
  h2:
    console:
      enabled: true
      path: /h2-console

jwt:
  secret: YQ7N3TpCRs+BEO2Zd5GxH/yVvjDA7wdFZj4eEzDI5iQ=
  expiration: 3600000 # 1 hour